spring:
  datasource:
    url: jdbc:mysql://maria_db:3306/beerstock
    driverClassName: org.mariadb.jdbc.Driver
    username: admin
    password: admin
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect